package registrohuespedes;

import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;


public class ConsultaHabitaciones extends javax.swing.JFrame {
 
    HabitacionTableModel modeloHabitaciones = new HabitacionTableModel();

    public ConsultaHabitaciones() {
        initComponents();
        inicializarColumnas();
    }


//codigo generado por ide
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBAgregarFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Habitaciones disponibles");

        jTable1.setModel(modeloHabitaciones);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jBAgregarFila.setText("AgregarFila");
        jBAgregarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAgregarFila)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jBAgregarFila)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// fin de codigo generado por ide
    

//programacion de eventos

    private void jBAgregarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarFilaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();
        Object nuevo[] = {"5D", new Integer(5), new Integer(3), new Double(50)};
        temp.addRow(nuevo);
    }//GEN-LAST:event_jBAgregarFilaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int clics = evt.getClickCount();
        int row = jTable1.rowAtPoint(evt.getPoint());
        HabitacionTableModel habitacionTableModel = (HabitacionTableModel) jTable1.getModel();
        //La acción se realizará cuando se realiza un doble clic
        if(clics == 2){
          String habitacionSeleccionada = (String) habitacionTableModel.habitaciones.get(row).getNumero();
          RegistroCliente registroCliente = new RegistroCliente(habitacionSeleccionada);
          registroCliente.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    //codigo generado por ide
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {//este metodo main no se ejecuta, ya que inicie desde Principal y ese main carga por lo tanto este main de aca no se llega a ejecutar, amenos que desde aca corramos el programa, en ese caso se ejecuta este y obviamente el otro no
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaHabitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
//////////////////////////////////////////////////////////////////////////////////////////////////////
/// fin de codigo generado por ide


    private void inicializarColumnas() {
        TableColumnModel tColumnModel=new DefaultTableColumnModel();
        for (int i = 0; i < modeloHabitaciones.getColumnCount()/*4*/; i++) {
            TableColumn col = new TableColumn(i);
            switch (i) {
                case 0:
                     col.setHeaderValue("Número");
                    break;
                case 1:
                     col.setHeaderValue("Nivel");
                    break;
                case 2:
                     col.setHeaderValue("Tipo");
                    break;
                case 3:
                     col.setHeaderValue("Precio");
                    break;
                default:
                    throw new AssertionError();
            }        
          tColumnModel.addColumn(col);
        }
        jTable1.setColumnModel(tColumnModel);
    }
}
